apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: backend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: backend
        image: registry.gitlab.com/webenable/cms/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: COUCHDB_URL
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: COUCHDB_URL
        - name: VALKEY_URL
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: VALKEY_URL
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: GIN_MODE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: webenable-cms-secrets
              key: JWT_SECRET
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webenable-cms-secrets
              key: ADMIN_PASSWORD
        - name: SESSION_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: SESSION_DOMAIN
        - name: SESSION_SECURE
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: SESSION_SECURE
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: CORS_ORIGINS
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
      imagePullSecrets:
      - name: gitlab-registry-secret 