apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/component: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 