
services:
  db:
    image: couchdb:3
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data

  cache:
    image: docker.io/valkey/valkey:alpine3.22
    restart: always
    ports:
      - "6379:6379"
    command: valkey-server --requirepass valkeypassword --appendonly yes
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "valkeypassword", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - cache
    environment:
      - COUCHDB_URL=http://admin:password@db:5984/
      - VALKEY_URL=redis://:valkeypassword@cache:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - SESSION_DOMAIN=localhost
      - SESSION_SECURE=false
      - CORS_ORIGINS=http://localhost:3000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
      - cache
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - BACKEND_URL=http://backend:8080

volumes:
  couchdb_data:
  valkey_data:
