apiVersion: v1
kind: Service
metadata:
  name: admin-panel-service
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: admin-panel
spec:
  selector:
    app.kubernetes.io/component: admin-panel
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP 