apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: frontend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: registry.gitlab.com/webenable/cms/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: NEXT_PUBLIC_API_URL
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: BACKEND_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      imagePullSecrets:
      - name: gitlab-registry-secret 