apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP 