apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cms
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cms-backend:latest  # Update with your registry
        ports:
        - containerPort: 8080
        env:
        - name: COUCHDB_URL
          valueFrom:
            configMapKeyRef:
              name: cms-config
              key: COUCHDB_URL
        - name: VALKEY_URL
          valueFrom:
            configMapKeyRef:
              name: cms-config
              key: VALKEY_URL
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: cms-config
              key: GIN_MODE
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cms-secrets
              key: COUCHDB_PASSWORD
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cms-secrets
              key: VALKEY_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cms-secrets
              key: JWT_SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: cms-secrets
              key: ENCRYPTION_KEY
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cms
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: cms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
