apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomization
data:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    namespace: cms
    
    resources:
    - namespace.yaml
    - database.yaml
    - cache.yaml
    - backend.yaml
    - frontend.yaml
    - ingress.yaml
    
    # Apply common labels
    commonLabels:
      app.kubernetes.io/name: cms
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/managed-by: kustomize
    
    # Image transformations
    images:
    - name: cms-backend
      newTag: latest
    - name: cms-frontend
      newTag: latest
