apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-monitor.yaml
  - pod-disruption-budget.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/component: monitoring 