apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: valkey
spec:
  selector:
    app.kubernetes.io/component: valkey
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP 