apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webenable-cms-dev

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: admin-panel

configMapGenerator:
  - name: webenable-cms-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - ADMIN_NODE_ENV=development
      - GIN_MODE=debug
      - SESSION_SECURE=false
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://frontend-service:3000,http://admin-panel-service:3001

secretGenerator:
  - name: webenable-cms-secrets
    behavior: merge
    literals:
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - COUCHDB_PASSWORD=dev-couchdb-password
      - VALKEY_PASSWORD=dev-valkey-password

commonLabels:
  environment: development

commonAnnotations:
  environment: development 