apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: couchdb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: couchdb
    spec:
      serviceAccountName: couchdb-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: couchdb
        image: docker.io/couchdb:3
        ports:
        - containerPort: 5984
          name: http
        env:
        - name: COUCHDB_USER
          valueFrom:
            configMapKeyRef:
              name: webenable-cms-config
              key: COUCHDB_USER
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webenable-cms-secrets
              key: COUCHDB_PASSWORD
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
        livenessProbe:
          httpGet:
            path: /
            port: 5984
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5984
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-pvc 