apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: webenable-cms
  labels:
    app.kubernetes.io/component: couchdb
spec:
  selector:
    app.kubernetes.io/component: couchdb
  ports:
  - name: http
    port: 5984
    targetPort: 5984
    protocol: TCP
  type: ClusterIP 