apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webenable-cms-prod

resources:
  - ../../base

patches:
  - path: resource-limits-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: resource-limits-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: resource-limits-patch.yaml
    target:
      kind: Deployment
      name: admin-panel

configMapGenerator:
  - name: webenable-cms-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - ADMIN_NODE_ENV=production
      - GIN_MODE=release
      - SESSION_SECURE=true
      - CORS_ORIGINS=https://webenable-cms.com,https://admin.webenable-cms.com

secretGenerator:
  - name: webenable-cms-secrets
    behavior: merge
    literals:
      - JWT_SECRET=production-jwt-secret-change-this
      - COUCHDB_PASSWORD=production-couchdb-password
      - VALKEY_PASSWORD=production-valkey-password

commonLabels:
  environment: production

commonAnnotations:
  environment: production 