apiVersion: v1
kind: Secret
metadata:
  name: webenable-cms-secrets
  namespace: webenable-cms
type: Opaque
stringData:
  # JWT Configuration
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  
  # Database Passwords
  COUCHDB_PASSWORD: "dGR5FbtwrkTCEbl1xFQZikKw7rIazzA6"
  VALKEY_PASSWORD: "your-secure-cache-password"
  
  # Admin User
  ADMIN_PASSWORD: "/juk+vfdbNk6TICg"
  
  # TLS Certificates (base64 encoded)
  # tls.crt: ""
  # tls.key: ""
  
  # Docker Registry (if using private registry)
  # docker-username: ""
  # docker-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: webenable-cms
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICIiCgkJfQoJfQp9 