apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webenable-cms-staging

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: admin-panel

configMapGenerator:
  - name: webenable-cms-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - ADMIN_NODE_ENV=production
      - GIN_MODE=release
      - SESSION_SECURE=false
      - CORS_ORIGINS=https://staging.webenable.asia,https://admin-staging.webenable.asia

secretGenerator:
  - name: webenable-cms-secrets
    behavior: merge
    literals:
      - JWT_SECRET=staging-jwt-secret-change-this
      - COUCHDB_PASSWORD=staging-couchdb-password
      - VALKEY_PASSWORD=staging-valkey-password

commonLabels:
  environment: staging

commonAnnotations:
  environment: staging 